### ISSUE TITLE
Implement Stripe Terminal SDK iOS

### ISSUE THREAD

**Issue by nprail** [eventOneHQ/cordova-plugin-stripe-terminal#1]
### To-Do
- [ ] Implement Terminal iOS SDK
- [ ] Implement Terminal JS Bridge
### Resources
- [Stripe Terminal iOS SDK Docs](https://stripe.com/docs/terminal/ios)
- [Example App](https://github.com/stripe/stripe-terminal-ios/tree/master/Example)
- [React Native Stripe Terminal Bridge](https://github.com/theopolisme/react-native-stripe-terminal)

**Comment by jsitu** [comment]
Hi @nprail what's the status of this plugin right now?

**Comment by nprail** [comment]
@jsitu Unfortunately, it's mostly non-functional at the moment. I haven't had much time to work on it since May and I really don't know what I'm doing anyway. I'm a JS dev, not a Swift dev...

I am currently looking for someone to help complete it. If you know anyone who knows Swift and would be willing to help, please let me know.

**Comment by peterfeddo** [comment]
@jsitu I ended up building a Cordova implementation of the Stripe API for a client so we could use a BBPOS chipper payment from our Magento PWA frontend to Stripe. If you have questions about that implementation I can give you some ideas.

**Comment by jsitu** [comment]
Hi @peterfeddo that's exactly what I am looking for right now. We are building a mobile app using Ionic 3, and we would like to integrate with Stripe Terminal and allow users to use BBPOS chipper.

**Comment by nprail** [comment]
@peterfeddo would you be willing to contribute to this project? That use case is also why I created the project.

**Comment by peterfeddo** [comment]
@jsitu What I ended up doing was taking the stripe terminal swift example application and integrating with Cordova using the cordova-nativeview plugin. I considered building a React/JS PWA interface to connect with all the stripe terminal apis but decided against it to save time and resources. Also at the time of our development the Stripe terminal api was still in beta so many things were changing and keeping up with it would have been problematic. 

So in our architecture the PWA makes a request at checkout/payment to trigger the Swift Payment Controller using a request facilitated by the NativeView plugin. It receives parameters for the payment and passes them on to the payment controller. 

In the payment controller we check for pairing with the Chipper but we also have a pairing/discovery utility controller that we use NativeView to trigger from an admin section. If the app is paired/connected we wait for payment. When payment is successfully received we pass the response back to the PWA and close out the Swift payment controller.

This is just a rough idea of how our implementation works. Who knows if my implementation is the best way to accomplish this integration but at the end of the day it does work successfully.

**Comment by peterfeddo** [comment]
@nprail this implementation is too big in scope for me to take on as an open source project. I'm not even sure it would fit within a single cordova plugin with my architecture and some modifications that must be made to the cordova ios platform code. 

Maybe down the road as the Stripe Terminal API matures I'd consider developing something that provides 100% native javascript interfaces for all the functionality. As it stands right now I'd be reluctant to do an open source implementation using the NativeView approach I suggested above.

**Comment by nprail** [comment]
@peterfeddo Hmm, yeah, a more Cordova-native bridge would be best for an open-source project. Interesting approach, though!

**Comment by nprail** [comment]
@jsitu @peterfeddo on Wednesday I started actively working on this again with a new approach. Instead of creating a Cordova plugin I'm creating a [Capacitor](https://capacitor.ionicframework.com) plugin.

If you haven't heard of it, Capacitor is Ionic's relatively new alternative to Cordova. But the plugin architecture and documentation is far better than Cordova's. Since Wednesday I have implemented discovering readers, connecting, disconnecting, checking for and installing updates, and getting connection info. By the end of tomorrow I'll probably have basic payment capturing done as well.

You can check out that project here: https://github.com/eventonehq/capacitor-stripe-terminal Also, migrating from Cordova to Capacitor is pretty painless. They have great docs for that too.

**Comment by nprail** [comment]
Closing because of #2.
